#spring.application.name=Journal App
#server.servlet.context-path=/api
#spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.auto-index-creation=true

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
  application:
    name: Journal App

server:
  servlet:
    context-path: /api
  port: 8000

